---
target_user_id: "{{ ansible_user_id }}"
#
# YOU CAN CREATE XXX_LIST_FILES USING tools/export-apps-lists.sh
#
# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.

# ruby_gems_packages_list_file values will be merged to ruby_gems values
ruby_gems_packages_list_file: ""

# This list is complemented by {{ruby_gems_packages_list_file}}
ruby_gems: []
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A

# npm_global_packages_list_file values will be merged to npm_packages values
npm_global_packages_list_file: ""

# This list is complemented by {{npm_global_packages_list_file}}
npm_packages: []
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A

# These PIP settings will install pip package GLOBALLY
# which is NOT advised, instead let the user setup its own pyenvs
#
# pip_packages_list_file values will be merged to pip_packages values
pip_packages_list_file: ""

# This list is complemented by {{pip_packages_list_file}}
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A
