---
- name:
  block:
  - name: Read NPM packages list from JSON file
    set_fact:
      npm_desired_global_packages: "{{ lookup('file', npm_global_packages_list_file) | from_json }}"
    ignore_errors: yes
    delegate_to: localhost

  - name: Update the list of Desired NPM global packages
    set_fact:
      npm_packages: "{{ npm_packages|default([]) + [{ 'name': item.key, 'state': 'present', 'version': item.value.version }] }}"
    with_dict: "{{ npm_desired_global_packages.dependencies }}"
  when:
    - npm_global_packages_list_file is defined
    - npm_global_packages_list_file | length > 0

- name: Install global NPM packages.
  npm:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    global: yes
    executable: "{{ item.executable | default(omit) }}"
  with_items: "{{ npm_packages }}"
  become: "{{ target_user_id != ansible_user_id }}"
  become_user: "{{ target_user_id }}"
