---
- name: Load list of packages from external file
  block:
  - name: Read PIP packages list from file
    read_csv:
      path: "{{ pip_packages_list_file }}"
      fieldnames: name,version
      delimiter: ','
    register: pip_desired_packages
    ignore_errors: yes
    delegate_to: localhost

  - name: Update the list of Desired PIP packages
    set_fact:
      pip_packages: "{{ pip_packages|default([]) + [{ 'name': item.name, 'state': 'present', 'version': item.version }] }}"
    with_items: "{{ pip_desired_packages.list }}"
  when:
    - pip_packages_list_file is defined
    - pip_packages_list_file | length > 0

- name: Install global PIP packages.
  pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ item.executable | default(omit) }}"
  with_items: "{{ pip_packages }}"
  become: "{{ target_user_id != ansible_user_id }}"
  become_user: "{{ target_user_id }}"
