---

language: python
python: 2.7

install:
    - pip install ansible
    - pip install yamllint
    - pip install ansible-lint

script:
    - yamllint .
    - cd tests
    - ansible-lint site.yml
    - ansible-playbook site.yml --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/