---
- block:
  - name: Enter sudo password
    pause: prompt="Enter sudo password" echo=no
    register: prompt

  - name: Store sudo password in 'ansible_become_pass'
    set_fact: ansible_become_pass="{{ prompt.user_input }}"
  # end block
  when: ansible_become_pass is not defined or ansible_become_pass | length == 0
  no_log: yes
  run_once: yes

- name: Passwordless Sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%admin (.*)ALL\s'
    line: "{{ item.line }}"
    validate: /usr/sbin/visudo -cf %s
    mode: 0440
  loop:
    - {enable: 'yes', line: "%admin ALL=(ALL) NOPASSWD: ALL"}
    - {enable: 'no', line: "%admin ALL=(ALL) ALL"}
  when: item.enable|bool == passwordless_sudo|bool
  changed_when: no
  become: yes
