---
- block:
  - name: "Application Firewall"
    osx_defaults: { domain: '/Library/Preferences/com.apple.alf', key: "{{ item.0.key }}", type: "{{ item.0.type }}", value: "{{ item.1.value }}" }
    with_subelements:
      - "{{ ApplicationFirewall_Preferences }}"
      - value
    when: (item.0.key == 'globalstate' and item.1.name == ApplicationFirewall_GlobalState) or
          (item.0.key == 'allowdownloadsignedenabled' and item.1.name == ApplicationFirewall_AllowDownloadSigned) or
          (item.0.key == 'allowsignedenabled' and item.1.name == ApplicationFirewall_AllowSigned) or
          (item.0.key == 'loggingenabled' and item.1.name == ApplicationFirewall_Logging) or
          (item.0.key == 'loggingoption' and item.1.name == ApplicationFirewall_LoggingOption) or
          (item.0.key == 'stealthenabled' and item.1.name == ApplicationFirewall_Stealth)

  # the above block is run as superuser
  become: yes
