---
- block:
  - name: "Disk Images - Disable disk image verification"
    osx_defaults: { domain: 'com.apple.frameworks.diskimages', key: "{{ item.key }}", type: bool, value: "{{ item.value }}" }
    loop:
      - { key: 'skip-verify',        value: '{{ DiskImages_SkipVerify }}' }
      - { key: 'skip-verify-locked', value: '{{ DiskImages_SkipVerifyLocked }}' }
      - { key: 'skip-verify-remote', value: '{{ DiskImages_SkipVerifyRemote }}' }
    when: item.value | string | length > 0
  # Privilege escalation to `target_user_id` is only required for inner steps when
  # the `target_user_id` doesn't match the `ansible_user_id`
  become: "{{ target_user_id != ansible_user_id }}"
  become_user: "{{ target_user_id }}"
