---
- block:
  - name: "Language & Region"
    osx_defaults: { domain: 'NSGlobalDomain', key: "{{ item.key }}", type: "{{ item.type }}", value: "{{ item.value }}" }
    loop:
      # - { key: 'AppleLanguages',          type: 'array',  value: '{{ LanguageRegion_Languages }}' }
      - { key: 'AppleLocale',             type: 'string', value: '{{ LanguageRegion_Locale }}' }
      - { key: 'AppleMeasurementUnits',   type: 'string', value: '{{ LanguageRegion_MeasurementUnits }}' }
      - { key: 'AppleICUForce24HourTime', type: 'bool',   value: '{{ LanguageRegion_Force24HourTime }}' }
      - { key: 'AppleMetricUnits',        type: 'bool',   value: '{{ LanguageRegion_MetricUnits }}' }
    when: item.value | string | length > 0

  # Privilege escalation to `target_user_id` is only required for inner steps when
  # the `target_user_id` doesn't match the `ansible_user_id`
  become: "{{ target_user_id != ansible_user_id }}"
  become_user: "{{ target_user_id }}"
