---
- block:
  - name: "Spotlight - Building List of Indexing Items"
    set_fact:
      orderedItems: "{{ orderedItems| default([])  }} + [ '{{ item }}' ]"
    loop: "{{ Spotlight_OrderedItems }}"
    when: Spotlight_OrderedItems is defined

  - name: "Spotlight - Apply List of Indexing Items"
    osx_defaults: { domain: 'com.apple.spotlight', key: 'orderedItems', type: array, value: "{{ Spotlight_OrderedItems }}" }
    when: orderedItems is defined and orderedItems != []
    changed_when: no
    notify: Restart Spotlight
  # Privilege escalation to `target_user_id` is only required for inner steps when
  # the `target_user_id` doesn't match the `ansible_user_id`
  become: "{{ target_user_id != ansible_user_id }}"
  become_user: "{{ target_user_id }}"
