---
galaxy_info:
  author: Eric Lafargue
  description: Ansible role to configure defaults on OSX.
  license: BSD
  min_ansible_version: 2.0
  platforms:
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - system
    - osx
