---
- hosts: localhost
  connection: local

  pre_tasks:
    - name: Load ENV and Default Values
      include_tasks: load-env-values.yml

    - name: Load the Splinter base tasks
      include_tasks: load-profiles.yml

  roles:
    - role: marcomc.splinter_toolkit
      tags: ['always']

    - role: ctorgalson.macos_hostname
      when: configure_system|bool
      tags: ['osx']
      ignore_errors: yes

    - role: marcomc.macos_sophos_endpoint
      when: configure_sophos_endpoint|bool
      tags: ['non_mas']
      ignore_errors: yes

    - role: marcomc.macos_new_user
      when: create_new_user|bool
      tags: ['new-user']
      ignore_errors: yes

    - role: marcomc.user_ssh_config
      when: create_new_user|bool
      tags: ['new-user']
      ignore_errors: yes

    - role: marcomc.macos_filevault2
      when: configure_filevault|bool
      tags: ['osx']
      ignore_errors: yes

    - role: marcomc.homebrew_multi_user
      when: configure_homebrew|bool
      tags: ['homebrew']
      ignore_errors: yes
      # this position assumes/rquires that Homebrew is already installed by the splinter script

    - role: geerlingguy.homebrew
      when: configure_homebrew|bool
      tags: ['homebrew']
      ignore_errors: yes

    - role: marcomc.homebrew_autoupdate
      when: configure_homebrew|bool
      tags: ['homebrew']
      ignore_errors: yes

    - role: marcomc.splinter_extra_packages
      when: configure_extra_packages|bool
      tags: ['extra-packages']
      ignore_errors: yes

    - role: lafarer.osx-defaults
      when: configure_system|bool
      tags: ['osx']
      ignore_errors: yes

    - role: juju4.macos_apps_install
      when: install_macos_apps|bool
      tags: ['non_mas']
      ignore_errors: yes
      environments:
        PATH: "{{ gnubin_path }}:{{ ansible_env.PATH }}"

    - role: marcomc.macos_setapp
      when: configure_setapp|bool
      ignore_errors: yes

    - role: geerlingguy.mas
      when: install_mas_apps|bool
      tags: ['mas']
      ignore_errors: yes

    - role: marcomc.macos_macprefs
      when:
        - macprefs_regular_backup|int > 0
      tags: ['dotfiles']
      ignore_errors: yes

    - role: geerlingguy.dotfiles
      when:
        - configure_dotfiles|bool
        - restore_dotfiles_with_git|bool
      tags: ['dotfiles']
      ignore_errors: yes
      become: "{{ target_user_id != ansible_user_id }}"
      become_user: "{{ target_user_id }}"

  tasks:
    - name: Load the Splinter post provision tasks.
      include_role:
        name: marcomc.splinter_toolkit
        tasks_from: post-provision
      tags: ['always']

    - name: Run custom post-provision tasks.
      include_tasks: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
