---
homebrew_user:                             "{{ ansible_user_id }}"
homebrew_auto_update_for_all_shell_types:   no #  no: apply the settings only to the user's default shellcheck
                                               # yes: apply the settings to all the shell supported: bash, zsh and fish
homebrew_user_launch_agents_dir:            "/Users/{{ homebrew_user }}/Library/LaunchAgents"
homebrew_user_application_support_dir:      "/Users/{{ homebrew_user }}/Library/Application Support/"
homebrew_user_default_shell:                ""
homebrew_auto_update_plist:                 "{{ homebrew_user_launch_agents_dir }}/com.github.domt4.homebrew-autoupdate.plist"
homebrew_auto_update_updater:               "{{ homebrew_user_application_support_dir }}/com.github.domt4.homebrew-autoupdate/updater"

homebrew_auto_update_tap:                   'domt4/autoupdate'
homebrew_auto_update_dependencies:           [ 'terminal-notifier' ]
homebrew_auto_update_override_config:        no    # override any existing config
homebrew_auto_update_interval:               43200 # 12 hours
homebrew_auto_update_upgrade:                no    # yes: will uprgade all formulae and casks, no: will only update the homebrew database
homebrew_auto_update_cleanup:                no   
homebrew_auto_update_enable_notification:    no
homebrew_auto_update_tollerance:             300   # 5 minutes
...
