repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.24.2
    hooks:
      - id: yamllint
  - repo: https://github.com/ansible/ansible-lint
    rev: v4.2.0
    hooks:
      - id: ansible-lint